/* ===========================
   MADPLAN — Opskriftskartotek
   =========================== */

const RECIPES = [

  // ── KLASSISK DANSK ──────────────────────────────────────────────────────────

  {
    id: 'frikadeller',
    name: 'Frikadeller med kartofler og brun sovs',
    category: 'klassisk',
    tags: ['klassisk dansk', 'børnevenlig', 'familie'],
    dietary: [],
    ingredients: ['svinekød', 'løg', 'æg', 'mel', 'mælk', 'smør', 'kartofler'],
  },
  {
    id: 'hakkebøf',
    name: 'Hakkebøf med bløde løg og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'hurtig', 'børnevenlig'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'løg', 'smør', 'kartofler'],
  },
  {
    id: 'stegt-flæsk',
    name: 'Stegt flæsk med persillesovs og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'hurtig'],
    dietary: [],
    ingredients: ['flæsk', 'kartofler', 'persille', 'smør', 'mel', 'mælk'],
  },
  {
    id: 'flæskesteg',
    name: 'Flæskesteg med rødkål og brunede kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend', 'festmad'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['svinekød', 'kartofler', 'rødkål', 'æbler', 'laurbær'],
  },
  {
    id: 'biksemad',
    name: 'Biksemad med spejlæg',
    category: 'klassisk',
    tags: ['klassisk dansk', 'restemat', 'hurtig'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['kartofler', 'pølse', 'løg', 'æg', 'smør'],
  },
  {
    id: 'æggekage',
    name: 'Æggekage med bacon og purløg',
    category: 'klassisk',
    tags: ['klassisk dansk', 'hurtig', 'billig'],
    dietary: [],
    ingredients: ['æg', 'bacon', 'purløg', 'mel', 'mælk', 'smør'],
  },
  {
    id: 'karbonader',
    name: 'Karbonader med kartoffelsalat og remoulade',
    category: 'klassisk',
    tags: ['klassisk dansk', 'børnevenlig'],
    dietary: [],
    ingredients: ['svinekød', 'rasp', 'æg', 'smør', 'kartofler'],
  },
  {
    id: 'labskovs',
    name: 'Skipper labskovs',
    category: 'klassisk',
    tags: ['klassisk dansk', 'comfort food', 'vinter'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'kartofler', 'løg', 'laurbær'],
  },
  {
    id: 'medister',
    name: 'Medisterpølse med kartofler og rødkål',
    category: 'klassisk',
    tags: ['klassisk dansk', 'enkel'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['medisterpølse', 'kartofler', 'rødkål'],
  },
  {
    id: 'svinekam',
    name: 'Stegt svinekam med persillesovs og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend'],
    dietary: [],
    ingredients: ['svinekød', 'kartofler', 'persille', 'smør', 'mel', 'mælk'],
  },
  {
    id: 'boller-i-karry',
    name: 'Boller i karry med ris',
    category: 'klassisk',
    tags: ['klassisk dansk', 'børnevenlig', 'familie'],
    dietary: [],
    ingredients: ['oksekød', 'svinekød', 'løg', 'karry', 'mel', 'smør', 'mælk', 'ris'],
  },
  {
    id: 'brændende-kærlighed',
    name: 'Brændende kærlighed med bacon og løg',
    category: 'klassisk',
    tags: ['klassisk dansk', 'comfort food', 'børnevenlig'],
    dietary: ['glutenfri'],
    ingredients: ['kartofler', 'bacon', 'løg', 'smør', 'mælk'],
  },
  {
    id: 'svensk-pølseret',
    name: 'Svensk pølseret med kartofler og sennepssovs',
    category: 'klassisk',
    tags: ['skandinavisk', 'hurtig', 'børnevenlig'],
    dietary: ['glutenfri'],
    ingredients: ['pølse', 'kartofler', 'løg', 'fløde', 'sennep', 'smør'],
  },
  {
    id: 'mørbradgryde',
    name: 'Mørbradgryde med champignon og flødesovs',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend', 'festmad'],
    dietary: ['glutenfri'],
    ingredients: ['svinekød', 'champignon', 'bacon', 'løg', 'fløde', 'kartofler'],
  },
  {
    id: 'baconruller',
    name: 'Baconruller i kartoffelfad med grønt',
    category: 'klassisk',
    tags: ['klassisk dansk', 'ovnret', 'familie'],
    dietary: ['glutenfri'],
    ingredients: ['bacon', 'kartofler', 'broccoli', 'løg', 'fløde', 'ost'],
  },
  {
    id: 'tærte-porre-bacon',
    name: 'Tærte med porre og bacon',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend', 'frokost'],
    dietary: [],
    ingredients: ['bacon', 'porre', 'æg', 'fløde', 'ost', 'mel', 'smør'],
  },

  // ── KYLLING ─────────────────────────────────────────────────────────────────

  {
    id: 'ovnkylling',
    name: 'Ovnstegt hel kylling med rosmarin og rodfrugter',
    category: 'kød',
    tags: ['weekend', 'klassisk'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['kylling', 'kartofler', 'gulerødder', 'løg', 'hvidløg', 'rosmarin', 'citron'],
  },
  {
    id: 'citronkylling',
    name: 'Citronkylling med ris og dampede grøntsager',
    category: 'kød',
    tags: ['hurtig', 'let'],
    dietary: ['glutenfri'],
    ingredients: ['kylling', 'citron', 'hvidløg', 'ris', 'broccoli', 'smør'],
  },
  {
    id: 'tikka-masala',
    name: 'Kylling tikka masala med basmatiris og raita',
    category: 'internationalt',
    tags: ['indisk', 'krydret'],
    dietary: ['glutenfri'],
    ingredients: ['kylling', 'tomat', 'fløde', 'løg', 'hvidløg', 'ingefær', 'ris', 'yoghurt'],
  },
  {
    id: 'butter-chicken',
    name: 'Butter chicken med naan og raita',
    category: 'internationalt',
    tags: ['indisk', 'mild'],
    dietary: [],
    ingredients: ['kylling', 'smør', 'tomat', 'fløde', 'løg', 'hvidløg', 'ingefær', 'yoghurt'],
  },
  {
    id: 'kylling-wok',
    name: 'Wok med kylling, grøntsager og sojasovs',
    category: 'internationalt',
    tags: ['asiatisk', 'hurtig', 'let'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['kylling', 'gulerødder', 'peberfrugt', 'sojasovs', 'hvidløg', 'ingefær', 'ris'],
  },
  {
    id: 'kyllingewrap',
    name: 'Kyllingewrap med avocado og krydderurt',
    category: 'internationalt',
    tags: ['hurtig', 'let', 'nem'],
    dietary: [],
    ingredients: ['kylling', 'tortilla', 'salat', 'tomat', 'rødløg', 'creme fraiche'],
  },
  {
    id: 'shawarma',
    name: 'Hjemmelavet kyllingeshawarma med pitabrød',
    category: 'internationalt',
    tags: ['mellemøstlig', 'populær'],
    dietary: [],
    ingredients: ['kylling', 'pitabrød', 'løg', 'tomat', 'salat', 'hvidløg', 'yoghurt'],
  },
  {
    id: 'kylling-fad',
    name: 'Kylling i fad med kartofler og timian',
    category: 'kød',
    tags: ['enkel', 'weekend'],
    dietary: ['glutenfri'],
    ingredients: ['kylling', 'kartofler', 'løg', 'hvidløg', 'timian', 'citron', 'smør'],
  },

  // ── OKSEKØD ─────────────────────────────────────────────────────────────────

  {
    id: 'bolognese',
    name: 'Spaghetti bolognese med revet parmesan',
    category: 'pasta',
    tags: ['italiensk', 'familie', 'fryseegnet'],
    dietary: [],
    ingredients: ['oksekød', 'spaghetti', 'tomat', 'løg', 'hvidløg', 'gulerødder', 'parmesan'],
  },
  {
    id: 'lasagne',
    name: 'Lasagne al forno med bechamelsovs',
    category: 'pasta',
    tags: ['italiensk', 'familie', 'fryseegnet'],
    dietary: [],
    ingredients: ['oksekød', 'lasagneplader', 'tomat', 'løg', 'hvidløg', 'mælk', 'mel', 'smør', 'ost'],
  },
  {
    id: 'chili-con-carne',
    name: 'Chili con carne med ris og rømme',
    category: 'internationalt',
    tags: ['mexicansk', 'fryseegnet', 'krydret'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'kidneybønner', 'tomat', 'løg', 'hvidløg', 'chili', 'ris'],
  },
  {
    id: 'tacos',
    name: 'Tacos med hakket oksekød og salsa',
    category: 'internationalt',
    tags: ['mexicansk', 'børnevenlig', 'familie'],
    dietary: [],
    ingredients: ['oksekød', 'tortilla', 'tomat', 'salat', 'løg', 'ost', 'majs'],
  },
  {
    id: 'burger',
    name: 'Hjemmelavede burgere med pommes frites',
    category: 'internationalt',
    tags: ['populær', 'weekend', 'børnevenlig'],
    dietary: [],
    ingredients: ['oksekød', 'burgerboller', 'salat', 'tomat', 'løg', 'ost', 'kartofler'],
  },

  // ── SVINEKØD ────────────────────────────────────────────────────────────────

  {
    id: 'pulled-pork',
    name: 'Pulled pork i burgerboller med coleslaw',
    category: 'internationalt',
    tags: ['weekend', 'populær'],
    dietary: [],
    ingredients: ['svinekød', 'burgerboller', 'hvidkål', 'gulerødder', 'æbler', 'mayonnaise'],
  },

  // ── FISK ────────────────────────────────────────────────────────────────────

  {
    id: 'laks-ovn',
    name: 'Ovnbagt laks med dild, kartofler og agurk-cremefraiche',
    category: 'fisk',
    tags: ['let', 'sund', 'hurtig'],
    dietary: ['glutenfri'],
    ingredients: ['laks', 'citron', 'dild', 'kartofler', 'smør', 'creme fraiche', 'agurk'],
  },
  {
    id: 'laks-pasta',
    name: 'Pasta med laks og cremet dild-flødesovs',
    category: 'fisk',
    tags: ['hurtig', 'let'],
    dietary: [],
    ingredients: ['laks', 'pasta', 'fløde', 'hvidløg', 'dild', 'citron'],
  },
  {
    id: 'bagels-laks',
    name: 'Bagels med røget laks, flødeost og dild',
    category: 'fisk',
    tags: ['frokost', 'hurtig', 'let'],
    dietary: [],
    ingredients: ['laks', 'bagels', 'flødeost', 'dild', 'rødløg', 'citron'],
  },
  {
    id: 'fiskefrikadeller',
    name: 'Fiskefrikadeller med remoulade og kogte kartofler',
    category: 'fisk',
    tags: ['klassisk dansk'],
    dietary: [],
    ingredients: ['fisk', 'æg', 'mel', 'dild', 'kartofler', 'løg'],
  },
  {
    id: 'torsk-paneret',
    name: 'Paneret torsk med remoulade, ærter og pommes frites',
    category: 'fisk',
    tags: ['klassisk', 'børnevenlig'],
    dietary: [],
    ingredients: ['torsk', 'rasp', 'æg', 'kartofler', 'ærter', 'citron'],
  },
  {
    id: 'fiskesuppe',
    name: 'Cremet fiskesuppe med grøntsager og dild',
    category: 'fisk',
    tags: ['suppe', 'sund'],
    dietary: ['glutenfri'],
    ingredients: ['fisk', 'gulerødder', 'løg', 'fløde', 'kartofler', 'dild'],
  },
  {
    id: 'rejer-hvidløg',
    name: 'Rejer stegt i hvidløgssmør med brød og citron',
    category: 'fisk',
    tags: ['hurtig', 'festmad'],
    dietary: [],
    ingredients: ['rejer', 'smør', 'hvidløg', 'persille', 'citron', 'brød'],
  },

  // ── PASTA ───────────────────────────────────────────────────────────────────

  {
    id: 'carbonara',
    name: 'Pasta carbonara med bacon og parmesan',
    category: 'pasta',
    tags: ['italiensk', 'hurtig'],
    dietary: [],
    ingredients: ['spaghetti', 'bacon', 'æg', 'parmesan', 'hvidløg'],
  },
  {
    id: 'pasta-pesto',
    name: 'Pasta med pesto, kylling og cherrytomater',
    category: 'pasta',
    tags: ['italiensk', 'hurtig'],
    dietary: [],
    ingredients: ['pasta', 'kylling', 'pesto', 'tomat', 'mozzarella', 'parmesan', 'hvidløg'],
  },
  {
    id: 'pasta-rejer',
    name: 'Linguine med rejer, hvidløg og persille',
    category: 'pasta',
    tags: ['italiensk', 'festmad'],
    dietary: [],
    ingredients: ['pasta', 'rejer', 'hvidløg', 'smør', 'persille', 'citron', 'tomat'],
  },
  {
    id: 'pasta-primavera',
    name: 'Pasta primavera med årstidens grøntsager og fløde',
    category: 'pasta',
    tags: ['vegetarisk', 'forår'],
    dietary: ['vegetarisk'],
    ingredients: ['pasta', 'broccoli', 'gulerødder', 'ærter', 'løg', 'hvidløg', 'fløde', 'parmesan'],
  },
  {
    id: 'pasta-kylling-bacon-karry',
    name: 'Pasta med kylling, bacon, karrydressing og spinat',
    category: 'pasta',
    tags: ['populær', 'hurtig'],
    dietary: [],
    ingredients: ['pasta', 'kylling', 'bacon', 'spinat', 'karry', 'mayonnaise', 'fløde', 'løg'],
  },

  // ── VEGETAR ─────────────────────────────────────────────────────────────────

  {
    id: 'dahl',
    name: 'Røde linser dahl med kokosmælk, basmatiris og naan',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'indisk'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['linser', 'kokosmælk', 'tomat', 'løg', 'hvidløg', 'ingefær', 'karry', 'ris'],
  },
  {
    id: 'kikærte-karry',
    name: 'Kikærtekarry med spinat, kokosmælk og basmatiris',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'indisk'],
    dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'],
    ingredients: ['kikærter', 'spinat', 'tomat', 'løg', 'hvidløg', 'ingefær', 'kokosmælk', 'karry', 'ris'],
  },
  {
    id: 'kikærtegryde',
    name: 'Kikærtegryde med tomat, paprika og feta',
    category: 'vegetar',
    tags: ['vegetarisk', 'hurtig', 'mellemøstlig'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['kikærter', 'tomat', 'peberfrugt', 'løg', 'hvidløg', 'feta', 'spinat'],
  },
  {
    id: 'grøntsagssuppe',
    name: 'Hjemmelavet grøntsagssuppe med brød',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'sund'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['gulerødder', 'løg', 'selleri', 'kartofler', 'persille', 'brød'],
  },
  {
    id: 'tomatsuppe',
    name: 'Cremet tomatsuppe med croutoner',
    category: 'vegetar',
    tags: ['vegetarisk', 'hurtig'],
    dietary: ['vegetarisk'],
    ingredients: ['tomat', 'løg', 'hvidløg', 'fløde', 'smør', 'brød'],
  },
  {
    id: 'falafler',
    name: 'Hjemmelavede falafler med hummus og pitabrød',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'mellemøstlig'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['kikærter', 'løg', 'hvidløg', 'persille', 'spidskommen', 'pitabrød', 'tomat', 'salat'],
  },
  {
    id: 'risotto',
    name: 'Champignonrisotto med parmesan og timian',
    category: 'vegetar',
    tags: ['italiensk', 'vegetarisk', 'weekend'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['risottoris', 'champignon', 'løg', 'hvidløg', 'parmesan', 'smør', 'fløde'],
  },

  // ── INTERNATIONALT ──────────────────────────────────────────────────────────

  {
    id: 'okonomiyaki',
    name: 'Okonomiyaki — japansk inspireret madpandekage',
    category: 'internationalt',
    tags: ['japansk', 'anderledes', 'hurtig'],
    dietary: [],
    ingredients: ['hvidkål', 'æg', 'mel', 'bacon', 'sojasovs', 'mayonnaise', 'purløg'],
  },
  {
    id: 'fried-rice',
    name: 'Stegt ris med æg, grøntsager og sojasovs',
    category: 'internationalt',
    tags: ['asiatisk', 'restemat', 'hurtig'],
    dietary: ['vegetarisk', 'glutenfri', 'laktosefri'],
    ingredients: ['ris', 'æg', 'sojasovs', 'løg', 'gulerødder', 'ærter', 'hvidløg'],
  },

  // ── FRA ARLA.DK ──────────────────────────────────────────────────────────────

  { id: 'quinoa-bowl-kylling', name: 'Quinoa bowl med kyllingedeller', category: 'kød', tags: ['sund', 'bowl', 'kylling'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['quinoa', 'kyllingedeller', 'avocado', 'agurk', 'cherrytomater', 'babyspinat', 'tahindressing'] },
  { id: 'linselasagne', name: 'Linselasagne', category: 'vegetar', tags: ['vegetarisk', 'lasagne', 'protein'], dietary: ['vegetarisk'], ingredients: ['linser', 'lasagneplader', 'hakkede tomater', 'løg', 'hvidløg', 'bechamelsauce', 'mozzarella'] },
  { id: 'kylling-i-karry', name: 'Kylling i karry', category: 'kød', tags: ['kylling', 'karry', 'dansk variant'], dietary: ['glutenfri'], ingredients: ['kyllingefilet', 'karry', 'løg', 'fløde', 'ris', 'bananer', 'kokosmælk'] },
  { id: 'marry-me-koedboller', name: 'Marry me kødboller', category: 'kød', tags: ['kødboller', 'cremet', 'italiensk'], dietary: [], ingredients: ['hakket svinekød', 'fløde', 'soltørrede tomater', 'hvidløg', 'parmesan', 'spinat', 'pasta'] },
  { id: 'teriyaki-nudler', name: 'Teriyaki nudler', category: 'internationalt', tags: ['asiatisk', 'nudler', 'hurtig'], dietary: ['laktosefri'], ingredients: ['ægnudler', 'kylling', 'teriyakisauce', 'sojasovs', 'sesamolie', 'forårsløg', 'sesam'] },
  { id: 'panang-karry', name: 'Panang karry', category: 'internationalt', tags: ['thai', 'karry', 'cremet'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['panangkarrypasta', 'kokosmælk', 'oksekød', 'peberfrugter', 'limeblade', 'fiskesauce', 'palmesukker'] },
  { id: 'linsedeller', name: 'Linsedeller', category: 'vegetar', tags: ['vegetarisk', 'vegansk', 'billig'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['linser', 'løg', 'hvidløg', 'spidskommen', 'mel', 'olie', 'salat'] },
  { id: 'stuvet-spidskaal', name: 'Stuvet spidskål med hakket oksekød', category: 'klassisk', tags: ['klassisk dansk', 'hurtig', 'billig'], dietary: ['glutenfri'], ingredients: ['spidskål', 'hakket oksekød', 'løg', 'fløde', 'smør', 'kartofler'] },
  { id: 'moussaka', name: 'Moussaka', category: 'internationalt', tags: ['græsk', 'aubergine', 'ovnret'], dietary: [], ingredients: ['hakket oksekød', 'aubergine', 'løg', 'hakkede tomater', 'kanel', 'bechamelsauce', 'ost'] },
  { id: 'chili-sin-carne', name: 'Chili sin carne', category: 'vegetar', tags: ['vegetarisk', 'vegansk', 'mexikansk'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['kidneybønner', 'majs', 'hakkede tomater', 'løg', 'peberfrugter', 'chili', 'ris'] },
  { id: 'pad-krapow', name: 'Pad Krapow (kylling med thai basilikum)', category: 'internationalt', tags: ['thai', 'hurtig', 'krydret'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingekød', 'thai basilikum', 'hvidløg', 'chilier', 'sojasovs', 'fiskesauce', 'æg', 'ris'] },
  { id: 'vegetarisk-enchiladas', name: 'Vegetarisk enchiladas', category: 'vegetar', tags: ['mexikansk', 'vegetarisk', 'ovnret'], dietary: ['vegetarisk'], ingredients: ['tortillabrød', 'sorte bønner', 'majs', 'rød enchiladas sauce', 'cheddarost', 'creme fraiche', 'avocado'] },
  { id: 'porretaerte', name: 'Porretærte', category: 'klassisk', tags: ['tærte', 'vegetarisk', 'hurtig'], dietary: ['vegetarisk'], ingredients: ['porrer', 'tærtedej', 'æg', 'fløde', 'ost', 'smør'] },
  { id: 'pasta-broccolicreme', name: 'Pasta med broccolicreme', category: 'pasta', tags: ['vegetarisk', 'hurtig', 'cremet'], dietary: ['vegetarisk'], ingredients: ['pasta', 'broccoli', 'flødeost', 'hvidløg', 'parmesan', 'olivenolie', 'citronskal'] },
  { id: 'nem-kyllingepande', name: 'Nem kyllingepande', category: 'kød', tags: ['kylling', 'hverdagsmad', 'hurtig'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingefilet', 'peberfrugter', 'løg', 'hvidløg', 'krydderier', 'olivenolie', 'ris'] },
  { id: 'orzo-svampe', name: 'Orzo gryde med svampe', category: 'vegetar', tags: ['vegetarisk', 'svampe', 'cremet'], dietary: ['vegetarisk'], ingredients: ['orzo', 'blandede svampe', 'løg', 'hvidløg', 'fløde', 'parmesan', 'frisk timian'] },
  { id: 'koteletter-fad', name: 'Koteletter i fad', category: 'klassisk', tags: ['klassisk dansk', 'ovnret', 'nem'], dietary: ['glutenfri'], ingredients: ['svinekoteletter', 'kartofler', 'løg', 'fløde', 'timian', 'smør'] },
  { id: 'karrysuppe', name: 'Karrysuppe', category: 'vegetar', tags: ['suppe', 'vegetarisk', 'varm'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['grøntsager', 'kokosmælk', 'karry', 'løg', 'hvidløg', 'ingefær', 'grøntsagsbouillon'] },
  { id: 'pasta-spinat-champignon', name: 'Pastaret med spinat og champignon', category: 'pasta', tags: ['vegetarisk', 'svampe', 'hurtig'], dietary: ['vegetarisk'], ingredients: ['pasta', 'champignon', 'spinat', 'hvidløg', 'fløde', 'parmesan', 'smør'] },
  { id: 'kyllingelaar-airfryer', name: 'Kyllingelår i airfryer', category: 'kød', tags: ['kylling', 'hurtig', 'sprød'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'hvidløg', 'paprika', 'olivenolie', 'salt', 'peber', 'timian'] },
  { id: 'pasta-roeget-laks', name: 'Pasta med røget laks og fløde', category: 'fisk', tags: ['laks', 'hurtig', 'cremet'], dietary: [], ingredients: ['pasta', 'røget laks', 'fløde', 'dild', 'citron', 'løg', 'parmesan'] },
  { id: 'biryani', name: 'Biryani', category: 'internationalt', tags: ['indisk', 'ris', 'krydret'], dietary: ['glutenfri'], ingredients: ['basmatiris', 'kylling', 'løg', 'yoghurt', 'safran', 'ghee', 'garam masala', 'koriander'] },
  { id: 'hytteostlasagne', name: 'Hytteostlasagne', category: 'pasta', tags: ['lasagne', 'sund', 'protein'], dietary: [], ingredients: ['lasagneplader', 'hakket oksekød', 'hytteost', 'ricotta', 'hakkede tomater', 'løg', 'mozzarella'] },
  { id: 'chilitaerte', name: 'Chilitærte', category: 'klassisk', tags: ['tærte', 'krydret', 'nem'], dietary: [], ingredients: ['tærtedej', 'hakket oksekød', 'chili', 'bønner', 'majs', 'cheddar', 'creme fraiche'] },
  { id: 'kartoffelsuppe', name: 'Kartoffelsuppe', category: 'klassisk', tags: ['suppe', 'dansk', 'cremet'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['kartofler', 'løg', 'hvidløg', 'grøntsagsbouillon', 'fløde', 'purløg', 'bacon'] },
  { id: 'one-pot-pasta-kylling', name: 'One pot pasta med kylling', category: 'pasta', tags: ['one-pot', 'kylling', 'hurtig'], dietary: [], ingredients: ['pasta', 'kyllingefilet', 'cherrytomater', 'hvidløg', 'spinat', 'bouillon', 'parmesan'] },
  { id: 'bagte-groentsager-feta', name: 'Bagte grøntsager med fetaost', category: 'vegetar', tags: ['vegetarisk', 'ovnret', 'sund'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['squash', 'peberfrugter', 'aubergine', 'cherrytomater', 'fetaost', 'olivenolie', 'friske urter'] },
  { id: 'groentsagslasagne', name: 'Grøntsagslasagne', category: 'vegetar', tags: ['vegetarisk', 'lasagne', 'ovnret'], dietary: ['vegetarisk'], ingredients: ['lasagneplader', 'squash', 'peberfrugter', 'spinat', 'bechamelsauce', 'hakkede tomater', 'ost'] },
  { id: 'pandestegt-laks', name: 'Pandestegt laks med citron', category: 'fisk', tags: ['laks', 'hurtig', 'sund'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['laksfilet', 'citron', 'hvidløg', 'smør', 'kapersurt', 'kartofler', 'salat'] },
  { id: 'gronkaalspasta', name: 'Grønkålspasta', category: 'pasta', tags: ['vegetarisk', 'sund', 'hurtig'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['pasta', 'grønkål', 'hvidløg', 'citronsaft', 'pinjekerner', 'olivenolie', 'chiliflager'] },
  { id: 'tortillasuppe', name: 'Tortillasuppe', category: 'internationalt', tags: ['mexikansk', 'suppe', 'krydret'], dietary: [], ingredients: ['kylling', 'hakkede tomater', 'majs', 'sorte bønner', 'tortillachips', 'cheddar', 'creme fraiche'] },
  { id: 'kylling-ovn-rodfrugter', name: 'Kylling i ovn med rodfrugter', category: 'kød', tags: ['kylling', 'ovnret', 'sund'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'gulerødder', 'pastinakker', 'selleri', 'kartofler', 'timian', 'olivenolie'] },
  { id: 'blomkaalssuppe', name: 'Blomkålssuppe', category: 'vegetar', tags: ['suppe', 'vegetarisk', 'cremet'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['blomkål', 'løg', 'hvidløg', 'grøntsagsbouillon', 'fløde', 'smør', 'ristede mandler'] },
  { id: 'risotto-svampe', name: 'Risotto med svampe', category: 'vegetar', tags: ['risotto', 'svampe', 'vegetarisk'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['risottoris', 'blandede svampe', 'løg', 'hvidløg', 'hvidvin', 'smør', 'parmesan'] },
  { id: 'krebinetter', name: 'Krebinetter med persillesovs', category: 'klassisk', tags: ['klassisk dansk', 'svine', 'hverdagsmad'], dietary: [], ingredients: ['hakket svinekød', 'rasp', 'æg', 'smør', 'persille', 'mel', 'mælk', 'kartofler'] },
  { id: 'tarteletter', name: 'Tarteletfyld med høns og asparges', category: 'klassisk', tags: ['klassisk dansk', 'festmad', 'retro'], dietary: [], ingredients: ['tarteletter', 'kylling', 'hvide asparges', 'ærter', 'gulerødder', 'bechamelsauce', 'smør'] },

  // ── FRA VALDEMARSRO (familiefavoritter) ──────────────────────────────────────

  { id: 'halloumi-stroganoff', name: 'Halloumi stroganoff med kartoffelmos', category: 'vegetar', tags: ['vegetarisk', 'cremet', 'hurtig'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['halloumi', 'champignon', 'løg', 'fløde', 'paprika', 'sennep', 'kartofler'] },
  { id: 'vegetar-boller-i-karry', name: 'Vegetariske boller i karry', category: 'vegetar', tags: ['vegetarisk', 'karry', 'familie'], dietary: ['vegetarisk'], ingredients: ['kikærter', 'kokosmælk', 'karry', 'løg', 'hvidløg', 'mel', 'ris'] },
  { id: 'vegetar-bourguignon', name: 'Vegetarisk bourguignon med svampe', category: 'vegetar', tags: ['vegetarisk', 'rødvin', 'vinterret'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['portobellosvampe', 'gulerødder', 'løg', 'rødvin', 'tomatpuré', 'timian', 'kartofler'] },
  { id: 'pasta-moerbrad-tomatfloede', name: 'Pasta med mørbrad i tomatflødesauce', category: 'pasta', tags: ['mørbrad', 'cremet', 'festmad'], dietary: [], ingredients: ['svinemørbrad', 'pasta', 'fløde', 'hakkede tomater', 'hvidløg', 'løg', 'parmesan'] },
  { id: 'pastasalat-kylling-karry', name: 'Pastasalat med kylling og karrydressing', category: 'kød', tags: ['kylling', 'salat', 'kold ret'], dietary: [], ingredients: ['pasta', 'kyllingefilet', 'karry', 'mayonnaise', 'agurk', 'majs', 'løg'] },
  { id: 'lasagnette', name: 'Lasagnette', category: 'pasta', tags: ['lasagne', 'lille format', 'hurtig'], dietary: [], ingredients: ['lasagneplade strimler', 'hakket svinekød', 'tomatsugo', 'løg', 'ricotta', 'mozzarella', 'basilikum'] },
  { id: 'marry-me-chicken', name: 'Marry Me Chicken', category: 'kød', tags: ['kylling', 'cremet', 'soltørrede tomater'], dietary: ['glutenfri'], ingredients: ['kyllingebryst', 'soltørrede tomater', 'fløde', 'hvidløg', 'parmesan', 'basilikum', 'olivenolie'] },
  { id: 'baconruller-kartoffelfad', name: 'Baconruller i kartoffelfad med grønt', category: 'klassisk', tags: ['bacon', 'ovnret', 'familie'], dietary: [], ingredients: ['baconruller', 'kartofler', 'løg', 'fløde', 'timian', 'gulerødder', 'smør'] },
  { id: 'kylling-sennepssauce', name: 'Kylling i cremet sennepssauce', category: 'kød', tags: ['kylling', 'cremet', 'sennep'], dietary: ['glutenfri'], ingredients: ['kyllingefilet', 'dijonsennep', 'fløde', 'hvidløg', 'løg', 'timian', 'kartofler'] },
  { id: 'cheeseburger-tacos', name: 'Cheeseburger tacos', category: 'internationalt', tags: ['tacos', 'burger', 'sjov mad'], dietary: [], ingredients: ['hakket oksekød', 'tacobrød', 'cheddar', 'salat', 'tomat', 'løg', 'burgerdressing'] },
  { id: 'texmex-risret', name: 'Texmex risret med oksekød', category: 'internationalt', tags: ['mexikansk', 'ris', 'one-pot'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['hakket oksekød', 'ris', 'majs', 'sorte bønner', 'hakkede tomater', 'tacokrydderi', 'peberfrugter'] },
  { id: 'one-pot-tortellini', name: 'One pot tortellini suppe', category: 'pasta', tags: ['suppe', 'one-pot', 'hurtig'], dietary: [], ingredients: ['tortellini', 'spinat', 'hakkede tomater', 'bouillon', 'hvidløg', 'løg', 'parmesan'] },
  { id: 'tacosuppe', name: 'Tacosuppe', category: 'internationalt', tags: ['mexikansk', 'suppe', 'nem'], dietary: ['glutenfri'], ingredients: ['hakket oksekød', 'hakkede tomater', 'majs', 'kidneybønner', 'tacokrydderi', 'bouillon', 'creme fraiche'] },
  { id: 'one-pot-pasta', name: 'One pot pasta', category: 'pasta', tags: ['one-pot', 'hurtig', 'nem'], dietary: [], ingredients: ['pasta', 'hakkede tomater', 'løg', 'hvidløg', 'spinat', 'bouillon', 'parmesan'] },
  { id: 'poelsehorn', name: 'Pølsehorn', category: 'klassisk', tags: ['børnevenlig', 'nem', 'hurtig'], dietary: [], ingredients: ['gærdejthorn', 'pølser', 'sennep', 'ketchup'] },
  { id: 'kyllingenuggets', name: 'Kyllinge nuggets', category: 'kød', tags: ['kylling', 'børnevenlig', 'sprød'], dietary: [], ingredients: ['kyllingebryst', 'rasp', 'æg', 'mel', 'paprika', 'olivenolie', 'dip'] },
  { id: 'asiatisk-sproedt-flaesk', name: 'Asiatisk sprødt flæsk med nudler', category: 'internationalt', tags: ['asiatisk', 'svinekød', 'sprød'], dietary: ['laktosefri'], ingredients: ['svinekød', 'nudler', 'sojasovs', 'sesamolie', 'ingefær', 'hvidløg', 'karamelliserede løg'] },
  { id: 'vegetar-cowboytoast', name: 'Vegetar cowboytoast', category: 'vegetar', tags: ['vegetarisk', 'toast', 'hurtig'], dietary: ['vegetarisk'], ingredients: ['brød', 'bønner i tomatsauce', 'æg', 'cheddar', 'avocado', 'cherrytomater'] },
  { id: 'kartoffelvafler-burrata', name: 'Kartoffelvafler med ovnbagt grønt og burrata', category: 'vegetar', tags: ['vegetarisk', 'vafler', 'anderledes'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['kartofler', 'æg', 'mel', 'burrata', 'squash', 'cherrytomater', 'olivenolie'] },
  { id: 'bagt-tomatsuppe', name: 'Bagt tomatsuppe', category: 'vegetar', tags: ['suppe', 'vegetarisk', 'ovnbagt'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['cherrytomater', 'hvidløg', 'løg', 'olivenolie', 'grøntsagsbouillon', 'basilikum', 'fløde'] },
  { id: 'vegetar-sloppy-joes', name: 'Vegetarisk sloppy joes burger', category: 'vegetar', tags: ['vegetarisk', 'burger', 'nem'], dietary: ['vegetarisk'], ingredients: ['linser', 'hakkede tomater', 'løg', 'peberfrugter', 'worcestershiresauce', 'burgerbolle', 'ost'] },
  { id: 'vegetar-quesadillas', name: 'Vegetar quesadillas med stegte bønner', category: 'vegetar', tags: ['mexikansk', 'vegetarisk', 'hurtig'], dietary: ['vegetarisk'], ingredients: ['tortillabrød', 'bønner', 'cheddar', 'majs', 'avocado', 'creme fraiche'] },
  { id: 'ramsloegs-pasta', name: 'Ramsløgspasta med burrata og ærter', category: 'pasta', tags: ['forår', 'vegetarisk', 'sæsonbestemt'], dietary: ['vegetarisk'], ingredients: ['pasta', 'ramsløg', 'burrata', 'ærter', 'olivenolie', 'citronsaft', 'parmesan'] },
  { id: 'one-pot-vegetar-pasta', name: 'One pot vegetar pasta med tomatflødesauce', category: 'pasta', tags: ['vegetarisk', 'one-pot', 'cremet'], dietary: ['vegetarisk'], ingredients: ['pasta', 'hakkede tomater', 'fløde', 'hvidløg', 'spinat', 'løg', 'parmesan'] },
  { id: 'cheeseburgersuppe', name: 'Cheeseburgersuppe med grøntsager', category: 'kød', tags: ['suppe', 'oksekød', 'sjov mad'], dietary: [], ingredients: ['hakket oksekød', 'kartofler', 'gulerødder', 'cheddar', 'bouillon', 'løg', 'hvidløg'] },
  { id: 'hvidkaalssuppe', name: 'Hvidkålssuppe', category: 'klassisk', tags: ['suppe', 'dansk', 'vinter'], dietary: ['vegetarisk', 'laktosefri'], ingredients: ['hvidkål', 'kartofler', 'løg', 'bouillon', 'gulerødder', 'timian', 'fløde'] },
  { id: 'chicken-caesar-tacos', name: 'Chicken cæsar tacos', category: 'kød', tags: ['kylling', 'tacos', 'salat'], dietary: [], ingredients: ['kyllingefilet', 'tacobrød', 'salat', 'parmesan', 'cæsardressing', 'bacon', 'krutonger'] },
  { id: 'gnocchi-svampesauce', name: 'Gnocchi i svampesauce', category: 'pasta', tags: ['gnocchi', 'svampe', 'vegetarisk'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['gnocchi', 'blandede svampe', 'fløde', 'hvidløg', 'parmesan', 'timian', 'smør'] },
  { id: 'millionlinser', name: 'Millionlinser', category: 'vegetar', tags: ['vegetarisk', 'billig', 'protein'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['linser', 'hakkede tomater', 'løg', 'hvidløg', 'spidskommen', 'gurkemeje', 'spinat'] },
  { id: 'loegtaerte', name: 'Løgtærte', category: 'klassisk', tags: ['tærte', 'løg', 'vegetarisk'], dietary: ['vegetarisk'], ingredients: ['tærtedej', 'løg', 'æg', 'fløde', 'ost', 'timian', 'smør'] },
  { id: 'grydestegt-kylling', name: 'Grydestegt kylling med kartofler og agurkesalat', category: 'kød', tags: ['kylling', 'klassisk', 'søndagsmad'], dietary: ['glutenfri'], ingredients: ['hel kylling', 'kartofler', 'smør', 'agurk', 'eddike', 'dild', 'hvidløg'] },
  { id: 'boef-lindstroem', name: 'Bøf Lindstrøm', category: 'klassisk', tags: ['klassisk dansk', 'bøf', 'rødbeder'], dietary: ['glutenfri'], ingredients: ['hakket oksekød', 'rødbeder', 'løg', 'kapers', 'kartofler', 'smør', 'æg'] },
  { id: 'koedboller-svampesauce', name: 'Kødboller i svampesauce', category: 'kød', tags: ['kødboller', 'svampe', 'cremet'], dietary: [], ingredients: ['hakket svinekød', 'champignon', 'fløde', 'løg', 'bouillon', 'kartofler', 'frisk persille'] },
  { id: 'biksemad-ovn', name: 'Biksemad i ovnen med kold bearnaise', category: 'klassisk', tags: ['restemat', 'ovnret', 'dansk'], dietary: ['glutenfri'], ingredients: ['kartofler', 'kød', 'løg', 'rødbeder', 'æg', 'bearnaisesauce', 'smør'] },
  { id: 'torsk-pakker', name: 'Torsk i pakker med grønt', category: 'fisk', tags: ['fisk', 'ovnret', 'nem'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['torsk', 'cherrytomater', 'oliven', 'kapers', 'olivenolie', 'citron', 'kartofler'] },
  { id: 'kaalfad-oksekoed', name: 'Kålfad med hakket oksekød', category: 'klassisk', tags: ['ovnret', 'kål', 'dansk'], dietary: ['glutenfri'], ingredients: ['hvidkål', 'hakket oksekød', 'løg', 'hakkede tomater', 'ris', 'bouillon'] },
  { id: 'katsu-kylling', name: 'Katsu kylling', category: 'internationalt', tags: ['japansk', 'sprød', 'kylling'], dietary: [], ingredients: ['kyllingebryst', 'rasp', 'æg', 'mel', 'katsu curry sauce', 'ris', 'spidskål'] },
  { id: 'risotto-kylling', name: 'Risotto med kylling', category: 'kød', tags: ['risotto', 'kylling', 'cremet'], dietary: ['glutenfri'], ingredients: ['risottoris', 'kyllingefilet', 'hvidløg', 'løg', 'hvidvin', 'bouillon', 'parmesan'] },
  { id: 'poelsegryde', name: 'Pølsegryde', category: 'klassisk', tags: ['pølse', 'hurtig', 'børnevenlig'], dietary: ['glutenfri'], ingredients: ['pølser', 'kartofler', 'løg', 'hakkede tomater', 'paprika', 'bouillon'] },
  { id: 'pulled-chicken-bowl', name: 'Bowl med pulled chicken og guacamole', category: 'kød', tags: ['kylling', 'bowl', 'mexikansk'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'avocado', 'majs', 'sorte bønner', 'ris', 'limesaft', 'koriander'] },
  { id: 'kylling-pastasuppe', name: 'Kylling pastasuppe med grøntsager', category: 'kød', tags: ['suppe', 'kylling', 'pasta'], dietary: [], ingredients: ['kylling', 'pasta', 'gulerødder', 'selleri', 'løg', 'bouillon', 'persille'] },
  { id: 'bagte-tomater-orzo', name: 'Bagte krydrede tomater med orzo', category: 'vegetar', tags: ['vegetarisk', 'ovnret', 'sommer'], dietary: ['vegetarisk'], ingredients: ['cherrytomater', 'orzo', 'hvidløg', 'olivenolie', 'basilikum', 'oliven', 'fetaost'] },
  { id: 'mexicansk-suppe-oksekoed', name: 'Mexicansk suppe med oksekød', category: 'internationalt', tags: ['mexikansk', 'suppe', 'krydret'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['hakket oksekød', 'hakkede tomater', 'kidneybønner', 'majs', 'chili', 'spidskommen', 'limesaft'] },
  { id: 'taquitos', name: 'Taquitos med oksekød og majs', category: 'internationalt', tags: ['mexikansk', 'sprød', 'nem'], dietary: [], ingredients: ['tortillabrød', 'hakket oksekød', 'majs', 'cheddar', 'tacokrydderi', 'salsa', 'creme fraiche'] },
  { id: 'gnocchi-sommersalat', name: 'Gnocchi sommersalat', category: 'vegetar', tags: ['gnocchi', 'salat', 'sommer'], dietary: ['vegetarisk'], ingredients: ['gnocchi', 'cherrytomater', 'rucola', 'fetaost', 'oliven', 'olivenolie', 'citronsaft'] },
  { id: 'graeske-hakkebuffe', name: 'Græske hakkebøffer med tzatziki', category: 'internationalt', tags: ['græsk', 'oksekød', 'tzatziki'], dietary: ['glutenfri'], ingredients: ['hakket oksekød', 'hvidløg', 'oregano', 'tzatziki', 'pitabrød', 'tomat', 'rødløg'] },
  { id: 'pasta-friske-tomater', name: 'Pasta med friske tomater og hvidløg', category: 'pasta', tags: ['vegetarisk', 'sommer', 'nem'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['pasta', 'cherrytomater', 'hvidløg', 'basilikum', 'olivenolie', 'chiliflager'] },
  { id: 'bbq-kylling-salat', name: 'BBQ kylling ranch salat', category: 'kød', tags: ['kylling', 'salat', 'bbq'], dietary: ['glutenfri'], ingredients: ['kyllingefilet', 'bbqsauce', 'ranchsauce', 'majs', 'cherrytomater', 'salat', 'cheddar'] },
  { id: 'fiskefilet-tatarsauce', name: 'Fiskefilet med tatarsauce og kartofler', category: 'fisk', tags: ['fisk', 'klassisk', 'nem'], dietary: [], ingredients: ['fiskefileter', 'tatarsauce', 'kartofler', 'citron', 'rasp', 'smør', 'ærter'] },
  { id: 'pulled-chicken-burger', name: 'Pulled chicken burger', category: 'kød', tags: ['kylling', 'burger', 'cremet'], dietary: [], ingredients: ['kyllingelår', 'burgerbolle', 'coleslaw', 'bbqsauce', 'agurk', 'rødløg'] },
  { id: 'vegetar-korma', name: 'Vegetar korma med blomkål og kikærter', category: 'vegetar', tags: ['vegetarisk', 'indisk', 'mild'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['blomkål', 'kikærter', 'kokosmælk', 'løg', 'ingefær', 'garam masala', 'ris'] },
  { id: 'fiskekager-bowl', name: 'Fiskekager i bowl med ris og asiatisk mayo', category: 'fisk', tags: ['fisk', 'bowl', 'asiatisk'], dietary: [], ingredients: ['fiskekager', 'ris', 'agurk', 'edamame', 'sesamolie', 'sojamayo', 'forårsløg'] },
  { id: 'vegetar-braendende-kaerlighed', name: 'Vegetarisk brændende kærlighed', category: 'vegetar', tags: ['klassisk dansk', 'vegetarisk', 'komfort'], dietary: ['vegetarisk'], ingredients: ['kartofler', 'løg', 'rødbeder', 'smør', 'plantebaseret kød', 'lakridsrod', 'frisk persille'] },

  // ── FRA MADENSVERDEN.DK ────────────────────────────────────────────────────────

  { id: 'kyllingebryst-spinat', name: 'Kyllingebryst med spinat og hvidløg', category: 'kød', tags: ['kylling', 'hurtig', 'sund'], dietary: ['glutenfri'], ingredients: ['kyllingebryst', 'spinat', 'hvidløg', 'fløde', 'parmesan', 'olivenolie', 'kartofler'] },
  { id: 'jaegerboef', name: 'Jægerbøf', category: 'klassisk', tags: ['klassisk dansk', 'bøf', 'svampe'], dietary: [], ingredients: ['svinekød', 'champignon', 'bacon', 'løg', 'fløde', 'rødvin', 'kartofler'] },
  { id: 'kartoffelgratin-oksekoed', name: 'Kartoffelgratin med oksekød', category: 'klassisk', tags: ['ovnret', 'oksekød', 'cremet'], dietary: ['glutenfri'], ingredients: ['kartofler', 'hakket oksekød', 'fløde', 'løg', 'hvidløg', 'ost', 'timian'] },
  { id: 'millionkylling', name: 'Millionkylling', category: 'kød', tags: ['kylling', 'nem', 'billig'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'hakkede tomater', 'løg', 'peberfrugter', 'hvidløg', 'paprika', 'ris'] },
  { id: 'pastasalat-boenner-kylling', name: 'Pastasalat med bønner og kylling', category: 'kød', tags: ['kylling', 'salat', 'kold ret'], dietary: [], ingredients: ['pasta', 'kylling', 'hvide bønner', 'basilikumsolie', 'cherrytomater', 'rødløg', 'parmesan'] },
  { id: 'one-pot-moerbrad-ris', name: 'One pot mørbrad med ris', category: 'kød', tags: ['mørbrad', 'one-pot', 'nem'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['svinemørbrad', 'ris', 'løg', 'hvidløg', 'bouillon', 'peberfrugter', 'paprika'] },
  { id: 'aeggekage-stegt-flaesk', name: 'Æggekage med stegt flæsk', category: 'klassisk', tags: ['klassisk dansk', 'flæsk', 'hverdagsmad'], dietary: [], ingredients: ['æg', 'mel', 'mælk', 'stegt flæsk', 'purløg', 'smør', 'kartofler'] },
  { id: 'oksekoed-spidskaal-ovn', name: 'Hakket oksekød og spidskål i ovn', category: 'klassisk', tags: ['ovnret', 'dansk', 'nem'], dietary: ['glutenfri'], ingredients: ['hakket oksekød', 'spidskål', 'løg', 'hvidløg', 'fløde', 'kartofler', 'ost'] },
  { id: 'stegt-torsk-sennep', name: 'Stegt torsk med sennepssauce', category: 'fisk', tags: ['fisk', 'torsk', 'sennep'], dietary: ['glutenfri'], ingredients: ['torsk', 'dijonsennep', 'fløde', 'citron', 'smør', 'kartofler', 'purløg'] },
  { id: 'foraaersruller', name: 'Forårsruller med svinekød', category: 'internationalt', tags: ['asiatisk', 'sprød', 'svinekød'], dietary: ['laktosefri'], ingredients: ['rismelspapir', 'svinekød', 'vermicelli', 'gulerødder', 'spidskål', 'sojasovs', 'sødsur sauce'] },
  { id: 'laks-citronsmor', name: 'Laks med citronsmørsauce', category: 'fisk', tags: ['laks', 'hurtig', 'festmad'], dietary: ['glutenfri'], ingredients: ['laksfilet', 'smør', 'citron', 'hvidløg', 'kapersurt', 'frisk dild', 'kartofler'] },
  { id: 'oksesteg-rodfrugter', name: 'Oksesteg med rodfrugter', category: 'klassisk', tags: ['steg', 'søndag', 'klassisk dansk'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['oksesteg', 'gulerødder', 'pastinakker', 'selleri', 'rødvin', 'bouillon', 'timian'] },
  { id: 'svinekotelet-svampesauce', name: 'Svinekotelet med svampesauce', category: 'klassisk', tags: ['kotelet', 'svampe', 'hverdagsmad'], dietary: ['glutenfri'], ingredients: ['svinekoteletter', 'champignon', 'fløde', 'løg', 'timian', 'kartofler', 'smør'] },
  { id: 'hjemmelavet-pizza', name: 'Hjemmelavet pizza med kødsovs', category: 'internationalt', tags: ['pizza', 'børnevenlig', 'nem'], dietary: [], ingredients: ['pizzadej', 'hakkede tomater', 'hakket oksekød', 'mozzarella', 'oregano', 'løg', 'olivenolie'] },
  { id: 'fiskeburger', name: 'Fiskeburger med coleslaw', category: 'fisk', tags: ['burger', 'fisk', 'sprød'], dietary: [], ingredients: ['fiskefileter', 'burgerbolle', 'coleslaw', 'remoulade', 'salat', 'tomat', 'citron'] },
  { id: 'kylling-pesto-pasta', name: 'Kylling i pesto med pasta', category: 'pasta', tags: ['kylling', 'pesto', 'hurtig'], dietary: [], ingredients: ['pasta', 'kyllingefilet', 'grøn pesto', 'cherrytomater', 'parmesan', 'pinjekerner', 'rucola'] },
  { id: 'aertesuppe-bacon', name: 'Ærtesuppe med bacon', category: 'klassisk', tags: ['suppe', 'klassisk dansk', 'bacon'], dietary: ['glutenfri'], ingredients: ['gule ærter', 'bacon', 'løg', 'gulerødder', 'selleri', 'kartofler', 'sennep'] },
  { id: 'linsesuppe-karry', name: 'Linsesuppe med karry og kokosmælk', category: 'vegetar', tags: ['suppe', 'vegetarisk', 'vegansk'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['røde linser', 'kokosmælk', 'karry', 'løg', 'hvidløg', 'ingefær', 'spinat'] },
  { id: 'blomkaalsgratin', name: 'Blomkålsgratin med ost', category: 'vegetar', tags: ['vegetarisk', 'ovnret', 'cremet'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['blomkål', 'bechamelsauce', 'ost', 'smør', 'revet muskatnød', 'salt', 'peber'] },
  { id: 'paella', name: 'Paella med kylling og rejer', category: 'internationalt', tags: ['spansk', 'ris', 'festmad'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['paellarist', 'kylling', 'rejer', 'safran', 'paprika', 'hvidløg', 'grøntsager'] },
  { id: 'hakket-kalv-kartofler', name: 'Hakket kalv i fad med kartofler', category: 'klassisk', tags: ['kalv', 'ovnret', 'klassisk dansk'], dietary: ['glutenfri'], ingredients: ['hakket kalvekød', 'kartofler', 'løg', 'fløde', 'timian', 'bouillon', 'smør'] },
  { id: 'risotto-bacon-aerter', name: 'Risotto med bacon og ærter', category: 'pasta', tags: ['risotto', 'bacon', 'hurtig'], dietary: ['glutenfri'], ingredients: ['risottoris', 'bacon', 'ærter', 'parmesan', 'smør', 'hvidvin', 'bouillon'] },
  { id: 'wok-rejer-groentsager', name: 'Wok med rejer og grøntsager', category: 'internationalt', tags: ['asiatisk', 'rejer', 'hurtig'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['rejer', 'blandede grøntsager', 'sojasovs', 'hvidløg', 'ingefær', 'sesamolie', 'ris'] },
  { id: 'zucchini-tomattaerte', name: 'Zucchini og tomattærte', category: 'vegetar', tags: ['vegetarisk', 'tærte', 'sommer'], dietary: ['vegetarisk'], ingredients: ['tærtedej', 'zucchini', 'tomater', 'fetaost', 'æg', 'fløde', 'oregano'] },
  { id: 'kyllingefilet-citron-rosmarin', name: 'Kyllingefilet med citron og rosmarin', category: 'kød', tags: ['kylling', 'ovnret', 'mediterransk'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingefilet', 'citron', 'rosmarin', 'hvidløg', 'olivenolie', 'kartofler', 'salt'] },
  { id: 'svinefilet-aeble', name: 'Svinefilet i ovn med æble og løg', category: 'klassisk', tags: ['svinefilet', 'ovnret', 'dansk'], dietary: ['glutenfri'], ingredients: ['svinefilet', 'æbler', 'løg', 'rosmarin', 'smør', 'kartofler', 'æblecidereddike'] },
  { id: 'pasta-pesto-soltørrede', name: 'Pasta pesto med kylling og soltørrede tomater', category: 'pasta', tags: ['pesto', 'kylling', 'hurtig'], dietary: [], ingredients: ['pasta', 'kyllingefilet', 'grøn pesto', 'soltørrede tomater', 'rucola', 'parmesan', 'pinjekerner'] },

  // ── FRA MUMMUM.DK ─────────────────────────────────────────────────────────────

  { id: 'kylling-bolognese', name: 'Kyllinge bolognese', category: 'kød', tags: ['kylling', 'bolognese', 'pasta'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['hakket kylling', 'hakkede tomater', 'løg', 'hvidløg', 'gulerødder', 'pasta', 'olivenolie'] },
  { id: 'kylling-karahi', name: 'Kylling karahi', category: 'internationalt', tags: ['pakistansk', 'kylling', 'krydret'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'hakkede tomater', 'ingefær', 'hvidløg', 'chili', 'koriander', 'krydderier'] },
  { id: 'linsegryde-blomkaal', name: 'Linsegryde med blomkål og kartofler', category: 'vegetar', tags: ['vegetarisk', 'vegansk', 'varmt'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['linser', 'blomkål', 'kartofler', 'løg', 'hakkede tomater', 'karry', 'spinat'] },
  { id: 'mexicansk-pulled-pork', name: 'Mexicansk pulled pork', category: 'internationalt', tags: ['svinekød', 'mexikansk', 'slow cook'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['nakkefilet', 'chipotle', 'hvidløg', 'lime', 'tacokrydderi', 'tacobrød', 'coleslaw'] },
  { id: 'one-pot-rod-karry', name: 'One pot kylling i rød karry', category: 'kød', tags: ['kylling', 'karry', 'one-pot'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'rød karrypasta', 'kokosmælk', 'bambusskud', 'limeblade', 'fiskesauce', 'ris'] },
  { id: 'kyllingegryde-ris', name: 'Kyllingegryde med ris', category: 'kød', tags: ['kylling', 'gryde', 'nem'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'ris', 'bouillon', 'løg', 'hvidløg', 'gulerødder', 'timian'] },
  { id: 'oksegryde', name: 'Oksegryde', category: 'klassisk', tags: ['oksekød', 'gryde', 'vinter'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['oksekød', 'gulerødder', 'løg', 'selleri', 'rødvin', 'bouillon', 'timian'] },
  { id: 'veggie-curry', name: 'Veggie curry', category: 'vegetar', tags: ['vegetarisk', 'vegansk', 'karry'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['blandede grøntsager', 'kokosmælk', 'karrypasta', 'løg', 'hvidløg', 'ingefær', 'ris'] },
  { id: 'kylling-paprika-havreris', name: 'Kylling i cremet paprikasauce med havreris', category: 'kød', tags: ['kylling', 'paprika', 'cremet'], dietary: ['glutenfri'], ingredients: ['kyllingefilet', 'paprika', 'fløde', 'løg', 'hvidløg', 'havreris', 'smør'] },
  { id: 'gullasch', name: 'Gullasch med kartoffelmos', category: 'klassisk', tags: ['oksekød', 'ungarsk', 'krydret'], dietary: ['glutenfri'], ingredients: ['oksekød', 'paprika', 'løg', 'hakkede tomater', 'bouillon', 'spidskommen', 'kartofler'] },
  { id: 'efteraarsgryde', name: 'Efterårsgryde med kyllingelår', category: 'kød', tags: ['kylling', 'efterår', 'gryde'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'rodfrugter', 'æbler', 'bouillon', 'timian', 'løg', 'æblecidereddike'] },
  { id: 'spinatgryde-kylling', name: 'Spinatgryde med kylling', category: 'kød', tags: ['kylling', 'spinat', 'nem'], dietary: ['glutenfri'], ingredients: ['kyllingefilet', 'spinat', 'fløde', 'hvidløg', 'løg', 'parmesan', 'ris'] },
  { id: 'millionboef', name: 'Millionbøf med kartoffelmos', category: 'klassisk', tags: ['oksekød', 'klassisk dansk', 'hverdagsmad'], dietary: ['glutenfri'], ingredients: ['hakket oksekød', 'løg', 'gulerødder', 'hakkede tomater', 'kartofler', 'smør', 'mælk'] },
  { id: 'oksegryde-kikaerter', name: 'Oksekødsgryde med kikærter', category: 'kød', tags: ['oksekød', 'kikærter', 'krydret'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['oksekød', 'kikærter', 'hakkede tomater', 'løg', 'hvidløg', 'spidskommen', 'koriander'] },
  { id: 'chana-masala', name: 'Chana masala', category: 'vegetar', tags: ['indisk', 'vegetarisk', 'vegansk'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['kikærter', 'hakkede tomater', 'løg', 'hvidløg', 'ingefær', 'garam masala', 'koriander'] },
  { id: 'boef-stroganoff', name: 'Bøf stroganoff med oksemørbrad', category: 'kød', tags: ['oksekød', 'russisk', 'cremet'], dietary: ['glutenfri'], ingredients: ['oksemørbrad', 'champignon', 'løg', 'creme fraiche', 'sennep', 'paprika', 'ris'] },
  { id: 'paprikagryde', name: 'Paprikagryde med hakket oksekød', category: 'kød', tags: ['oksekød', 'paprika', 'nem'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['hakket oksekød', 'peberfrugter', 'løg', 'hakkede tomater', 'paprika', 'ris', 'hvidløg'] },
  { id: 'kyllingelaar-gryde', name: 'Kyllingelår i gryde med grøntsager', category: 'kød', tags: ['kylling', 'gryde', 'sund'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelår', 'gulerødder', 'selleri', 'løg', 'hvidvin', 'timian', 'bouillon'] },
  { id: 'dahl-soede-kartofler', name: 'Dahl med søde kartofler', category: 'vegetar', tags: ['indisk', 'vegetarisk', 'vegansk'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['røde linser', 'søde kartofler', 'kokosmælk', 'løg', 'hvidløg', 'ingefær', 'spidskommen'] },
  { id: 'indisk-kikaertegryde', name: 'Indisk kikærtegryde med peberfrugt og spinat', category: 'vegetar', tags: ['indisk', 'vegetarisk', 'protein'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['kikærter', 'peberfrugter', 'spinat', 'kokosmælk', 'løg', 'garam masala', 'hvidløg'] },
  { id: 'osso-bucco', name: 'Osso bucco', category: 'kød', tags: ['italiensk', 'festmad', 'kalv'], dietary: ['glutenfri'], ingredients: ['kalveskank', 'hvidvin', 'hakkede tomater', 'gulerødder', 'selleri', 'gremolata', 'risotto'] },
  { id: 'oksemoerbradgryde', name: 'Oksemørbradgryde', category: 'kød', tags: ['oksekød', 'mørbrad', 'festmad'], dietary: ['glutenfri'], ingredients: ['oksemørbrad', 'champignon', 'fløde', 'rødvin', 'løg', 'kartofler', 'frisk timian'] },
  { id: 'svinekaebers-rødvin', name: 'Rødvinsbraiserede svinekæber', category: 'kød', tags: ['svinekæber', 'rødvin', 'langsom tilberedning'], dietary: ['glutenfri'], ingredients: ['svinekæber', 'rødvin', 'gulerødder', 'løg', 'selleri', 'timian', 'kartoffelmos'] },
  { id: 'svinekaebers-sommer', name: 'Svinekæber ala dansk sommer', category: 'kød', tags: ['svinekæber', 'sommermad', 'festmad'], dietary: ['glutenfri'], ingredients: ['svinekæber', 'æblecider', 'æbler', 'timian', 'hvidløg', 'grøntsager', 'bær'] },
  { id: 'mexibowl', name: 'Mexibowl med braiseret nakkefilet', category: 'kød', tags: ['mexikansk', 'bowl', 'langsom tilberedning'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['nakkefilet', 'tacokrydderi', 'ris', 'sorte bønner', 'majs', 'avocado', 'salsa'] },
  { id: 'butterdej-texmex', name: 'Butterdej med oksekød og texmex', category: 'kød', tags: ['butterdej', 'mexikansk', 'nem'], dietary: [], ingredients: ['butterdej', 'hakket oksekød', 'majs', 'bønner', 'cheddar', 'creme fraiche', 'salsa'] },
  { id: 'fajitas', name: 'Fajitas med hjemmelavede tortillas', category: 'internationalt', tags: ['mexikansk', 'kylling', 'sjov mad'], dietary: ['laktosefri'], ingredients: ['kyllingefilet', 'tortillabrød', 'peberfrugter', 'løg', 'lime', 'guacamole', 'tacokrydderi'] },
  { id: 'kyllingeburger', name: 'Kyllingeburger', category: 'kød', tags: ['kylling', 'burger', 'nem'], dietary: [], ingredients: ['kyllingefilet', 'burgerbolle', 'salat', 'tomat', 'mayonnaise', 'agurk', 'sennep'] },
  { id: 'tomatsuppe-bacon', name: 'Tomatsuppe med bacon', category: 'klassisk', tags: ['suppe', 'bacon', 'hverdagsmad'], dietary: [], ingredients: ['hakkede tomater', 'bacon', 'løg', 'hvidløg', 'fløde', 'basilikum', 'brød'] },
  { id: 'laks-cremet-sauce', name: 'Laks i cremet sauce med tomater og spinat', category: 'fisk', tags: ['laks', 'cremet', 'hurtig'], dietary: ['glutenfri'], ingredients: ['laksfilet', 'cherrytomater', 'spinat', 'fløde', 'hvidløg', 'citron', 'kartofler'] },
  { id: 'moerbrad-bacon-champignon', name: 'Mørbrad i fad med bacon og champignon', category: 'klassisk', tags: ['mørbrad', 'ovnret', 'festmad'], dietary: ['glutenfri'], ingredients: ['svinemørbrad', 'bacon', 'champignon', 'cocktailpølser', 'fløde', 'kartofler', 'smør'] },
  { id: 'hasselback-kylling', name: 'Hasselback kylling med tomat og ost', category: 'kød', tags: ['kylling', 'ovnret', 'ost'], dietary: ['glutenfri'], ingredients: ['kyllingebryst', 'mozzarella', 'soltørrede tomater', 'basilikum', 'olivenolie', 'kartofler'] },
  { id: 'one-pot-thaisuppe', name: 'One pot thaisuppe', category: 'internationalt', tags: ['thai', 'suppe', 'one-pot'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kokosmælk', 'bouillon', 'rejer', 'risnudler', 'rød karrypasta', 'limeblade', 'ingefær'] },

  // ── SUPPLERENDE KLASSIKERE ─────────────────────────────────────────────────────

  { id: 'kyllingelaar-honning-soja', name: 'Kyllingelårfileter med honning og soja', category: 'kød', tags: ['kylling', 'asiatisk', 'nem'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingelårfileter', 'honning', 'sojasovs', 'hvidløg', 'ingefær', 'sesamolie', 'ris'] },
  { id: 'spaghetti-rejer-chorizo', name: 'Spaghetti med rejer og chorizo', category: 'pasta', tags: ['rejer', 'chorizo', 'krydret'], dietary: ['laktosefri'], ingredients: ['spaghetti', 'rejer', 'chorizo', 'hvidløg', 'cherrytomater', 'hvidvin', 'persille'] },
  { id: 'koteletter-aeblekompot', name: 'Pandestegte koteletter med æblekompot', category: 'klassisk', tags: ['klassisk dansk', 'kotelet', 'æble'], dietary: ['glutenfri'], ingredients: ['svinekoteletter', 'æbler', 'sukker', 'smør', 'kartofler', 'timian', 'sennep'] },
  { id: 'laks-dijon', name: 'Ovnbagt laks med dijonsennep og urter', category: 'fisk', tags: ['laks', 'ovnret', 'hurtig'], dietary: ['glutenfri'], ingredients: ['laksfilet', 'dijonsennep', 'honning', 'dild', 'citron', 'olivenolie', 'kartofler'] },
  { id: 'pasta-foraaersgroentsager-feta', name: 'Forårsgrøntsager med pasta og feta', category: 'pasta', tags: ['vegetarisk', 'forår', 'let'], dietary: ['vegetarisk'], ingredients: ['pasta', 'ærter', 'asparges', 'fetaost', 'citronskal', 'olivenolie', 'mynthe'] },
  { id: 'groen-thai-karry', name: 'Grøn thai karry med kylling', category: 'internationalt', tags: ['thai', 'karry', 'kylling'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingefilet', 'grøn karrypasta', 'kokosmælk', 'bambusskud', 'thai aubergine', 'limeblade', 'ris'] },
  { id: 'roed-thai-karry-rejer', name: 'Rød thai karry med rejer', category: 'internationalt', tags: ['thai', 'karry', 'rejer'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['rejer', 'rød karrypasta', 'kokosmælk', 'peberfrugter', 'limeblade', 'fiskesauce', 'ris'] },
  { id: 'butter-paneer', name: 'Indisk butter paneer', category: 'vegetar', tags: ['indisk', 'vegetarisk', 'cremet'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['paneer', 'hakkede tomater', 'smør', 'fløde', 'løg', 'hvidløg', 'ingefær', 'garam masala'] },
  { id: 'vegansk-dhal-spinat', name: 'Vegansk dhal med spinat', category: 'vegetar', tags: ['vegansk', 'indisk', 'protein'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['røde linser', 'spinat', 'kokosmælk', 'løg', 'hvidløg', 'ingefær', 'spidskommen'] },
  { id: 'bagt-feta-pasta', name: 'Bagt feta pasta', category: 'pasta', tags: ['vegetarisk', 'viral', 'nem'], dietary: ['vegetarisk'], ingredients: ['fetaost', 'pasta', 'cherrytomater', 'hvidløg', 'olivenolie', 'basilikum', 'chiliflager'] },
  { id: 'ziti-al-forno', name: 'Ziti al forno', category: 'pasta', tags: ['italiensk', 'ovnret', 'festmad'], dietary: [], ingredients: ['ziti pasta', 'hakket oksekød', 'hakkede tomater', 'bechamelsauce', 'mozzarella', 'parmesan', 'løg'] },
  { id: 'steak-bearnaise', name: 'Steak med bearnaisesauce og pommes frites', category: 'kød', tags: ['bøf', 'festmad', 'klassisk'], dietary: ['glutenfri'], ingredients: ['oksebøf', 'bearnaisesauce', 'kartofler', 'smør', 'dragon', 'æggeblomme', 'skalotteløg'] },
  { id: 'pasta-arrabiata', name: 'Pasta arrabiata', category: 'pasta', tags: ['vegetarisk', 'krydret', 'hurtig'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['pasta', 'hakkede tomater', 'hvidløg', 'chiliflager', 'olivenolie', 'persille'] },
  { id: 'svamperisotto', name: 'Svamperisotto', category: 'vegetar', tags: ['risotto', 'vegetarisk', 'cremet'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['risottoris', 'blandede svampe', 'parmesan', 'smør', 'hvidvin', 'løg', 'hvidløg'] },
  { id: 'selleri-guleroed-suppe', name: 'Selleri- og gulerøddersuppe med ingefær', category: 'vegetar', tags: ['suppe', 'vegansk', 'vinter'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['knoldselleri', 'gulerødder', 'ingefær', 'løg', 'kokosmælk', 'bouillon', 'limesaft'] },
  { id: 'helstegt-kylling', name: 'Helstegt kylling med timian og citron', category: 'kød', tags: ['kylling', 'søndagsmad', 'klassisk'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['hel kylling', 'citron', 'timian', 'hvidløg', 'smør', 'kartofler', 'olivenolie'] },
  { id: 'torsk-pesto-tomater', name: 'Ovnbagt torsk med pesto og cherrytomater', category: 'fisk', tags: ['fisk', 'torsk', 'nem'], dietary: ['glutenfri'], ingredients: ['torsk', 'grøn pesto', 'cherrytomater', 'oliven', 'olivenolie', 'citron', 'kartofler'] },
  { id: 'samsa', name: 'Samsa med oksekød og løg', category: 'internationalt', tags: ['centralasiatisk', 'bagt dej', 'anderledes'], dietary: [], ingredients: ['butterdejtrianglar', 'hakket oksekød', 'løg', 'spidskommen', 'peber', 'smeltet smør'] },
  { id: 'ramen', name: 'Ramen med blødkogt æg og svinekød', category: 'internationalt', tags: ['japansk', 'suppe', 'nudler'], dietary: ['laktosefri'], ingredients: ['ramen nudler', 'svinekød', 'bouillon', 'sojasovs', 'mirin', 'æg', 'nori', 'forårsløg'] },
  { id: 'sushi-bowl', name: 'Sushi bowl med laks og avocado', category: 'fisk', tags: ['sushi', 'bowl', 'japansk'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['laks', 'sushiris', 'avocado', 'agurk', 'edamame', 'sojasovs', 'risvineddike'] },
  { id: 'bulgur-bowl', name: 'Bowl med bulgur, grillede grøntsager og hummus', category: 'vegetar', tags: ['vegetarisk', 'vegansk', 'sund'], dietary: ['vegetarisk', 'vegansk', 'laktosefri'], ingredients: ['bulgur', 'grillede grøntsager', 'hummus', 'oliven', 'fetaost', 'citron', 'friske urter'] },
  { id: 'enchiladas-kylling', name: 'Enchiladas med kylling og rød sauce', category: 'internationalt', tags: ['mexikansk', 'kylling', 'ovnret'], dietary: [], ingredients: ['tortillabrød', 'kylling', 'rød enchilada sauce', 'cheddar', 'creme fraiche', 'majs', 'avocado'] },
  { id: 'quesadillas-ost', name: 'Quesadillas med ost og jalapeño', category: 'vegetar', tags: ['mexikansk', 'vegetarisk', 'hurtig'], dietary: ['vegetarisk'], ingredients: ['tortillabrød', 'cheddar', 'jalapeño', 'majs', 'sorte bønner', 'creme fraiche', 'salsa'] },
  { id: 'nachos-pulled-pork', name: 'Nachos med pulled pork og salsa', category: 'internationalt', tags: ['mexikansk', 'sjov mad', 'deletallerken'], dietary: [], ingredients: ['tortillachips', 'pulled pork', 'cheddar', 'jalapeño', 'guacamole', 'creme fraiche', 'salsa'] },
  { id: 'aubergine-feta', name: 'Ovnbagt aubergine med fetafyld', category: 'vegetar', tags: ['vegetarisk', 'mediterransk', 'sund'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['aubergine', 'fetaost', 'cherrytomater', 'hvidløg', 'olivenolie', 'frisk oregano', 'ris'] },
  { id: 'stuffed-peberfrugter', name: 'Stuffed peberfrugter med ris og oksekød', category: 'kød', tags: ['ovnret', 'oksekød', 'ris'], dietary: ['glutenfri'], ingredients: ['peberfrugter', 'hakket oksekød', 'ris', 'hakkede tomater', 'løg', 'hvidløg', 'ost'] },
  { id: 'wok-oyster-sauce', name: 'Hakket oksekød i wok med oyster sauce', category: 'internationalt', tags: ['asiatisk', 'oksekød', 'hurtig'], dietary: ['laktosefri'], ingredients: ['hakket oksekød', 'oyster sauce', 'sojasovs', 'hvidløg', 'ingefær', 'forårsløg', 'ris'] },
  { id: 'kyllingesalat-mango', name: 'Kyllingesalat med mango og chilisauce', category: 'kød', tags: ['kylling', 'salat', 'sød-stærk'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['kyllingefilet', 'mango', 'chilisauce', 'salat', 'forårsløg', 'koriander', 'limesaft'] },
  { id: 'grillet-poelse', name: 'Grillet pølse med kartoffelmos og sennep', category: 'klassisk', tags: ['pølse', 'klassisk dansk', 'hurtig'], dietary: ['glutenfri'], ingredients: ['pølser', 'kartofler', 'smør', 'mælk', 'sennep', 'rødkål'] },
  { id: 'roedspatte', name: 'Stegt rødspætte med rejer og remoulade', category: 'fisk', tags: ['klassisk dansk', 'fisk', 'sommer'], dietary: [], ingredients: ['rødspætte', 'rejer', 'remoulade', 'citron', 'smør', 'kartofler', 'dild'] },
  { id: 'fiskefileter-ovn', name: 'Fiskefileter i ovn med kartofler og citron', category: 'fisk', tags: ['fisk', 'nem', 'sund'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['fiskefileter', 'kartofler', 'citron', 'olivenolie', 'hvidløg', 'timian'] },
  { id: 'krabbesalat', name: 'Krabbesalat med avocado og citron', category: 'fisk', tags: ['krabber', 'salat', 'festmad'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['krabbe', 'avocado', 'citron', 'mayonnaise', 'dild', 'agurk', 'rucola'] },
  { id: 'hjemmelavet-kebab', name: 'Hjemmelavet kebab med pitabrød', category: 'internationalt', tags: ['kebab', 'oksekød', 'hverdagsfestmad'], dietary: [], ingredients: ['hakket oksekød', 'pitabrød', 'salat', 'tomat', 'rødløg', 'tzatziki', 'hvidløgssauce'] },
  { id: 'kalvesteg', name: 'Kalvesteg med flødesauce og ris', category: 'klassisk', tags: ['kalv', 'klassisk dansk', 'festmad'], dietary: ['glutenfri'], ingredients: ['kalvesteg', 'fløde', 'bouillon', 'løg', 'timian', 'kartofler', 'ris'] },
  { id: 'kyllingestrimler-paprika', name: 'Kyllingestrimler med paprika og creme fraiche', category: 'kød', tags: ['kylling', 'hurtig', 'cremet'], dietary: ['glutenfri'], ingredients: ['kyllingefilet', 'peberfrugter', 'creme fraiche', 'paprika', 'løg', 'kartofler', 'smør'] },
  { id: 'pasta-brunet-smor', name: 'Pasta med brunet smør og salvie', category: 'pasta', tags: ['vegetarisk', 'italiensk', 'simpel'], dietary: ['vegetarisk'], ingredients: ['pasta', 'smør', 'frisk salvie', 'parmesan', 'sort peber', 'pinjekerner'] },
  { id: 'ovnbagt-kartoffelmos', name: 'Ovnbagt kartoffelmos med ost og bacon', category: 'klassisk', tags: ['kartofler', 'ovnret', 'komfort'], dietary: ['glutenfri'], ingredients: ['kartofler', 'bacon', 'ost', 'smør', 'mælk', 'purløg', 'creme fraiche'] },
  { id: 'oksehale', name: 'Oksehale i rødvinsauce', category: 'kød', tags: ['oksekød', 'slowfood', 'festmad'], dietary: ['glutenfri'], ingredients: ['oksehale', 'rødvin', 'gulerødder', 'løg', 'selleri', 'timian', 'kartoffelmos'] },
  { id: 'kyllingesuppe-perlebyg', name: 'Kyllingesuppe med perlebyg og grøntsager', category: 'kød', tags: ['suppe', 'kylling', 'sund'], dietary: [], ingredients: ['kylling', 'perlebyg', 'gulerødder', 'selleri', 'løg', 'persille', 'bouillon'] },
  { id: 'tomatsovs-koedboller-orzo', name: 'Tomatsovs med kødboller og orzo', category: 'kød', tags: ['kødboller', 'orzo', 'italiensk'], dietary: [], ingredients: ['hakket svinekød', 'orzo', 'hakkede tomater', 'løg', 'hvidløg', 'basilikum', 'parmesan'] },
  { id: 'groen-linsesuppe', name: 'Grøn linsesuppe med citron og koriander', category: 'vegetar', tags: ['suppe', 'vegansk', 'sund'], dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'], ingredients: ['grønne linser', 'løg', 'hvidløg', 'ingefær', 'citron', 'koriander', 'olivenolie'] },
  { id: 'pasta-artiskok', name: 'Pasta med artiskok og parmesan', category: 'pasta', tags: ['vegetarisk', 'italiensk', 'hurtig'], dietary: ['vegetarisk'], ingredients: ['pasta', 'artiskokhjerter', 'parmesan', 'hvidløg', 'olivenolie', 'citronsaft', 'rucola'] },
  { id: 'svineribben-bbq', name: 'Svineribben med BBQ glasur', category: 'kød', tags: ['ribben', 'bbq', 'weekend'], dietary: ['glutenfri', 'laktosefri'], ingredients: ['svineribben', 'bbqsauce', 'honning', 'sojasovs', 'hvidløg', 'paprika', 'coleslaw'] },
  { id: 'kylling-champignon-floede', name: 'Kyllingebryst med champignon og fløde', category: 'kød', tags: ['kylling', 'cremet', 'svampe'], dietary: ['glutenfri'], ingredients: ['kyllingebryst', 'champignon', 'fløde', 'hvidløg', 'løg', 'timian', 'kartofler'] },
  { id: 'fishcakes-kapers-dild', name: 'Fishcakes med kapers og dild', category: 'fisk', tags: ['fisk', 'nem', 'hurtig'], dietary: [], ingredients: ['fiskekød', 'kartofler', 'kapers', 'dild', 'æg', 'rasp', 'remoulade'] },
  { id: 'blomkaal-broccoli-gratin', name: 'Blomkål og broccoli gratin med ost', category: 'vegetar', tags: ['vegetarisk', 'ovnret', 'cremet'], dietary: ['vegetarisk', 'glutenfri'], ingredients: ['blomkål', 'broccoli', 'bechamelsauce', 'ost', 'smør', 'revet muskatnød', 'parmesan'] },
  { id: 'jordnoeddenudelsuppe', name: 'Jordnøddenudelsuppe med kylling og spidskål', category: 'kød', tags: ['asiatisk', 'suppe', 'jordnødder'], dietary: ['laktosefri'], ingredients: ['kylling', 'risnudler', 'jordnøddesmør', 'sojasovs', 'spidskål', 'ingefær', 'limesaft'] },

  // ── FRA VALDEMARSRO (nem hverdagsmad) ────────────────────────────────────────

  {
    id: 'sur-soed-groentsager',
    name: 'Sur-sød grøntsager',
    category: 'vegetar',
    tags: ['asiatisk', 'hurtig', 'farverig'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['peberfrugter', 'gulerødder', 'løg', 'ananas', 'sojasovs', 'eddike', 'sukker', 'maizena', 'ris'],
  },
  {
    id: 'nduja-pasta',
    name: 'Nduja Pasta',
    category: 'pasta',
    tags: ['italiensk', 'krydret', 'hurtig'],
    dietary: ['laktosefri'],
    ingredients: ['nduja', 'pasta', 'hakkede tomater', 'hvidløg', 'løg', 'olivenolie', 'parmesan'],
  },
  {
    id: 'marry-me-chicken-orzo',
    name: 'Marry Me Chicken Orzo med spinat',
    category: 'kød',
    tags: ['kylling', 'cremet', 'one-pot'],
    dietary: [],
    ingredients: ['kyllingefilet', 'orzo', 'spinat', 'cherrytomater', 'hvidløg', 'fløde', 'parmesan', 'basilikum', 'olivenolie'],
  },
  {
    id: 'pasta-bagte-tomater-kapers',
    name: 'Pasta med bagte tomater, kapers og oliven',
    category: 'pasta',
    tags: ['italiensk', 'vegetarisk', 'enkel'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['pasta', 'cherrytomater', 'kapers', 'sorte oliven', 'hvidløg', 'olivenolie', 'frisk basilikum'],
  },
  {
    id: 'ramsloegssuppe',
    name: 'Ramsløgssuppe med kartofler',
    category: 'vegetar',
    tags: ['suppe', 'forårsret', 'sæsonbestemt'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['ramsløg', 'kartofler', 'løg', 'hvidløg', 'grøntsagsbouillon', 'fløde', 'smør'],
  },
  {
    id: 'graesk-kartoffelfad',
    name: 'Græsk kartoffelfad med oksekød',
    category: 'kød',
    tags: ['græsk', 'ovnret', 'familie'],
    dietary: ['glutenfri'],
    ingredients: ['oksekød', 'kartofler', 'hakkede tomater', 'løg', 'hvidløg', 'kanel', 'oregano', 'olivenolie', 'feta'],
  },
  {
    id: 'ovnbagt-aeggekage',
    name: 'Ovnbagt æggekage med grønt',
    category: 'klassisk',
    tags: ['hurtig', 'billig', 'vegetarisk'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['æg', 'mælk', 'spinat', 'cherrytomater', 'fetaost', 'purløg', 'smør'],
  },
  {
    id: 'halloumi-curry',
    name: 'Halloumi Curry',
    category: 'vegetar',
    tags: ['vegetarisk', 'krydret', 'cremet'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['halloumi', 'kokosmælk', 'hakkede tomater', 'løg', 'hvidløg', 'ingefær', 'karry', 'spinat', 'ris'],
  },
  {
    id: 'vegetar-karrysuppe-kikaerter',
    name: 'Vegetar Karrysuppe med kikærter',
    category: 'vegetar',
    tags: ['suppe', 'vegetarisk', 'krydret', 'billig'],
    dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'],
    ingredients: ['kikærter', 'kokosmælk', 'hakkede tomater', 'løg', 'hvidløg', 'ingefær', 'karrypasta', 'spinat', 'limesaft'],
  },
  {
    id: 'sur-soed-nudelsalat',
    name: 'Sur-sød nudelsalat',
    category: 'internationalt',
    tags: ['asiatisk', 'salat', 'hurtig', 'kold'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['risnudler', 'agurk', 'gulerødder', 'forårsløg', 'koriander', 'jordnødder', 'limesaft', 'sojasovs', 'sesamolie', 'sukker'],
  },
  {
    id: 'vegetarisk-lasagnesuppe',
    name: 'Vegetarisk Lasagnesuppe',
    category: 'vegetar',
    tags: ['suppe', 'vegetarisk', 'komfort', 'one-pot'],
    dietary: ['vegetarisk'],
    ingredients: ['lasagneplader', 'hakkede tomater', 'løg', 'hvidløg', 'grøntsagsbouillon', 'ricotta', 'mozzarella', 'spinat', 'oregano'],
  },
  {
    id: 'pasta-roedbede',
    name: 'Pasta med rødbedesauce',
    category: 'pasta',
    tags: ['vegetarisk', 'farverig', 'cremet'],
    dietary: ['vegetarisk'],
    ingredients: ['pasta', 'rødbeder', 'fløde', 'hvidløg', 'løg', 'olivenolie', 'parmesan', 'frisk timian'],
  },
  {
    id: 'sellerisuppe',
    name: 'Sellerisuppe',
    category: 'vegetar',
    tags: ['suppe', 'vegetarisk', 'cremet', 'vinter'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['knoldselleri', 'løg', 'hvidløg', 'kartofler', 'grøntsagsbouillon', 'fløde', 'smør', 'æble'],
  },
  {
    id: 'spinatvafler-laks',
    name: 'Spinatvafler med røget laks',
    category: 'fisk',
    tags: ['fisk', 'anderledes', 'brunch'],
    dietary: [],
    ingredients: ['spinat', 'æg', 'mel', 'mælk', 'røget laks', 'cremefraiche', 'dild', 'citron', 'smør'],
  },
  {
    id: 'salsiccia-pasta',
    name: 'Salsiccia Pasta',
    category: 'pasta',
    tags: ['italiensk', 'hurtig', 'krydret'],
    dietary: [],
    ingredients: ['salsiccia', 'pasta', 'hakkede tomater', 'fløde', 'hvidløg', 'løg', 'fennikelfrø', 'parmesan', 'olivenolie'],
  },
  {
    id: 'pho-nudelsuppe',
    name: 'Pho nudelsuppe med oksekød',
    category: 'internationalt',
    tags: ['vietnamesisk', 'suppe', 'asiatisk'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'risnudler', 'oksebouillon', 'ingefær', 'løg', 'stjerneanis', 'kanel', 'forårsløg', 'bønnespirer', 'limesaft'],
  },
  {
    id: 'nem-koedsauce',
    name: 'Nem kødsauce med grøntsager',
    category: 'kød',
    tags: ['hurtig', 'børnevenlig', 'familie', 'hverdagsmad'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['hakket oksekød', 'løg', 'gulerødder', 'selleri', 'hakkede tomater', 'hvidløg', 'tomatsauce', 'pasta'],
  },
  {
    id: 'frikadeller-pandesauce',
    name: 'Frikadeller med pandesauce, agurk og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'familie', 'søndagsret'],
    dietary: [],
    ingredients: ['svinekød', 'løg', 'æg', 'mel', 'mælk', 'smør', 'kartofler', 'agurk', 'fløde', 'dild'],
  },

];
