/* ===========================
   MADPLAN — Opskriftskartotek
   =========================== */

const RECIPES = [

  // ── KLASSISK DANSK ──────────────────────────────────────────────────────────

  {
    id: 'frikadeller',
    name: 'Frikadeller med kartofler og brun sovs',
    category: 'klassisk',
    tags: ['klassisk dansk', 'børnevenlig', 'familie'],
    dietary: [],
    ingredients: ['svinekød', 'løg', 'æg', 'mel', 'mælk', 'smør', 'kartofler'],
  },
  {
    id: 'hakkebøf',
    name: 'Hakkebøf med bløde løg og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'hurtig', 'børnevenlig'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'løg', 'smør', 'kartofler'],
  },
  {
    id: 'stegt-flæsk',
    name: 'Stegt flæsk med persillesovs og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'hurtig'],
    dietary: [],
    ingredients: ['flæsk', 'kartofler', 'persille', 'smør', 'mel', 'mælk'],
  },
  {
    id: 'flæskesteg',
    name: 'Flæskesteg med rødkål og brunede kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend', 'festmad'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['svinekød', 'kartofler', 'rødkål', 'æbler', 'laurbær'],
  },
  {
    id: 'biksemad',
    name: 'Biksemad med spejlæg',
    category: 'klassisk',
    tags: ['klassisk dansk', 'restemat', 'hurtig'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['kartofler', 'pølse', 'løg', 'æg', 'smør'],
  },
  {
    id: 'æggekage',
    name: 'Æggekage med bacon og purløg',
    category: 'klassisk',
    tags: ['klassisk dansk', 'hurtig', 'billig'],
    dietary: [],
    ingredients: ['æg', 'bacon', 'purløg', 'mel', 'mælk', 'smør'],
  },
  {
    id: 'karbonader',
    name: 'Karbonader med kartoffelsalat og remoulade',
    category: 'klassisk',
    tags: ['klassisk dansk', 'børnevenlig'],
    dietary: [],
    ingredients: ['svinekød', 'rasp', 'æg', 'smør', 'kartofler'],
  },
  {
    id: 'labskovs',
    name: 'Skipper labskovs',
    category: 'klassisk',
    tags: ['klassisk dansk', 'comfort food', 'vinter'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'kartofler', 'løg', 'laurbær'],
  },
  {
    id: 'medister',
    name: 'Medisterpølse med kartofler og rødkål',
    category: 'klassisk',
    tags: ['klassisk dansk', 'enkel'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['medisterpølse', 'kartofler', 'rødkål'],
  },
  {
    id: 'svinekam',
    name: 'Stegt svinekam med persillesovs og kartofler',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend'],
    dietary: [],
    ingredients: ['svinekød', 'kartofler', 'persille', 'smør', 'mel', 'mælk'],
  },
  {
    id: 'boller-i-karry',
    name: 'Boller i karry med ris',
    category: 'klassisk',
    tags: ['klassisk dansk', 'børnevenlig', 'familie'],
    dietary: [],
    ingredients: ['oksekød', 'svinekød', 'løg', 'karry', 'mel', 'smør', 'mælk', 'ris'],
  },
  {
    id: 'brændende-kærlighed',
    name: 'Brændende kærlighed med bacon og løg',
    category: 'klassisk',
    tags: ['klassisk dansk', 'comfort food', 'børnevenlig'],
    dietary: ['glutenfri'],
    ingredients: ['kartofler', 'bacon', 'løg', 'smør', 'mælk'],
  },
  {
    id: 'svensk-pølseret',
    name: 'Svensk pølseret med kartofler og sennepssovs',
    category: 'klassisk',
    tags: ['skandinavisk', 'hurtig', 'børnevenlig'],
    dietary: ['glutenfri'],
    ingredients: ['pølse', 'kartofler', 'løg', 'fløde', 'sennep', 'smør'],
  },
  {
    id: 'mørbradgryde',
    name: 'Mørbradgryde med champignon og flødesovs',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend', 'festmad'],
    dietary: ['glutenfri'],
    ingredients: ['svinekød', 'champignon', 'bacon', 'løg', 'fløde', 'kartofler'],
  },
  {
    id: 'baconruller',
    name: 'Baconruller i kartoffelfad med grønt',
    category: 'klassisk',
    tags: ['klassisk dansk', 'ovnret', 'familie'],
    dietary: ['glutenfri'],
    ingredients: ['bacon', 'kartofler', 'broccoli', 'løg', 'fløde', 'ost'],
  },
  {
    id: 'tærte-porre-bacon',
    name: 'Tærte med porre og bacon',
    category: 'klassisk',
    tags: ['klassisk dansk', 'weekend', 'frokost'],
    dietary: [],
    ingredients: ['bacon', 'porre', 'æg', 'fløde', 'ost', 'mel', 'smør'],
  },

  // ── KYLLING ─────────────────────────────────────────────────────────────────

  {
    id: 'ovnkylling',
    name: 'Ovnstegt hel kylling med rosmarin og rodfrugter',
    category: 'kød',
    tags: ['weekend', 'klassisk'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['kylling', 'kartofler', 'gulerødder', 'løg', 'hvidløg', 'rosmarin', 'citron'],
  },
  {
    id: 'citronkylling',
    name: 'Citronkylling med ris og dampede grøntsager',
    category: 'kød',
    tags: ['hurtig', 'let'],
    dietary: ['glutenfri'],
    ingredients: ['kylling', 'citron', 'hvidløg', 'ris', 'broccoli', 'smør'],
  },
  {
    id: 'tikka-masala',
    name: 'Kylling tikka masala med basmatiris og raita',
    category: 'internationalt',
    tags: ['indisk', 'krydret'],
    dietary: ['glutenfri'],
    ingredients: ['kylling', 'tomat', 'fløde', 'løg', 'hvidløg', 'ingefær', 'ris', 'yoghurt'],
  },
  {
    id: 'butter-chicken',
    name: 'Butter chicken med naan og raita',
    category: 'internationalt',
    tags: ['indisk', 'mild'],
    dietary: [],
    ingredients: ['kylling', 'smør', 'tomat', 'fløde', 'løg', 'hvidløg', 'ingefær', 'yoghurt'],
  },
  {
    id: 'kylling-wok',
    name: 'Wok med kylling, grøntsager og sojasovs',
    category: 'internationalt',
    tags: ['asiatisk', 'hurtig', 'let'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['kylling', 'gulerødder', 'peberfrugt', 'sojasovs', 'hvidløg', 'ingefær', 'ris'],
  },
  {
    id: 'kyllingewrap',
    name: 'Kyllingewrap med avocado og krydderurt',
    category: 'internationalt',
    tags: ['hurtig', 'let', 'nem'],
    dietary: [],
    ingredients: ['kylling', 'tortilla', 'salat', 'tomat', 'rødløg', 'creme fraiche'],
  },
  {
    id: 'shawarma',
    name: 'Hjemmelavet kyllingeshawarma med pitabrød',
    category: 'internationalt',
    tags: ['mellemøstlig', 'populær'],
    dietary: [],
    ingredients: ['kylling', 'pitabrød', 'løg', 'tomat', 'salat', 'hvidløg', 'yoghurt'],
  },
  {
    id: 'kylling-fad',
    name: 'Kylling i fad med kartofler og timian',
    category: 'kød',
    tags: ['enkel', 'weekend'],
    dietary: ['glutenfri'],
    ingredients: ['kylling', 'kartofler', 'løg', 'hvidløg', 'timian', 'citron', 'smør'],
  },

  // ── OKSEKØD ─────────────────────────────────────────────────────────────────

  {
    id: 'bolognese',
    name: 'Spaghetti bolognese med revet parmesan',
    category: 'pasta',
    tags: ['italiensk', 'familie', 'fryseegnet'],
    dietary: [],
    ingredients: ['oksekød', 'spaghetti', 'tomat', 'løg', 'hvidløg', 'gulerødder', 'parmesan'],
  },
  {
    id: 'lasagne',
    name: 'Lasagne al forno med bechamelsovs',
    category: 'pasta',
    tags: ['italiensk', 'familie', 'fryseegnet'],
    dietary: [],
    ingredients: ['oksekød', 'lasagneplader', 'tomat', 'løg', 'hvidløg', 'mælk', 'mel', 'smør', 'ost'],
  },
  {
    id: 'chili-con-carne',
    name: 'Chili con carne med ris og rømme',
    category: 'internationalt',
    tags: ['mexicansk', 'fryseegnet', 'krydret'],
    dietary: ['glutenfri', 'laktosefri'],
    ingredients: ['oksekød', 'kidneybønner', 'tomat', 'løg', 'hvidløg', 'chili', 'ris'],
  },
  {
    id: 'tacos',
    name: 'Tacos med hakket oksekød og salsa',
    category: 'internationalt',
    tags: ['mexicansk', 'børnevenlig', 'familie'],
    dietary: [],
    ingredients: ['oksekød', 'tortilla', 'tomat', 'salat', 'løg', 'ost', 'majs'],
  },
  {
    id: 'burger',
    name: 'Hjemmelavede burgere med pommes frites',
    category: 'internationalt',
    tags: ['populær', 'weekend', 'børnevenlig'],
    dietary: [],
    ingredients: ['oksekød', 'burgerboller', 'salat', 'tomat', 'løg', 'ost', 'kartofler'],
  },

  // ── SVINEKØD ────────────────────────────────────────────────────────────────

  {
    id: 'pulled-pork',
    name: 'Pulled pork i burgerboller med coleslaw',
    category: 'internationalt',
    tags: ['weekend', 'populær'],
    dietary: [],
    ingredients: ['svinekød', 'burgerboller', 'hvidkål', 'gulerødder', 'æbler', 'mayonnaise'],
  },

  // ── FISK ────────────────────────────────────────────────────────────────────

  {
    id: 'laks-ovn',
    name: 'Ovnbagt laks med dild, kartofler og agurk-cremefraiche',
    category: 'fisk',
    tags: ['let', 'sund', 'hurtig'],
    dietary: ['glutenfri'],
    ingredients: ['laks', 'citron', 'dild', 'kartofler', 'smør', 'creme fraiche', 'agurk'],
  },
  {
    id: 'laks-pasta',
    name: 'Pasta med laks og cremet dild-flødesovs',
    category: 'fisk',
    tags: ['hurtig', 'let'],
    dietary: [],
    ingredients: ['laks', 'pasta', 'fløde', 'hvidløg', 'dild', 'citron'],
  },
  {
    id: 'bagels-laks',
    name: 'Bagels med røget laks, flødeost og dild',
    category: 'fisk',
    tags: ['frokost', 'hurtig', 'let'],
    dietary: [],
    ingredients: ['laks', 'bagels', 'flødeost', 'dild', 'rødløg', 'citron'],
  },
  {
    id: 'fiskefrikadeller',
    name: 'Fiskefrikadeller med remoulade og kogte kartofler',
    category: 'fisk',
    tags: ['klassisk dansk'],
    dietary: [],
    ingredients: ['fisk', 'æg', 'mel', 'dild', 'kartofler', 'løg'],
  },
  {
    id: 'torsk-paneret',
    name: 'Paneret torsk med remoulade, ærter og pommes frites',
    category: 'fisk',
    tags: ['klassisk', 'børnevenlig'],
    dietary: [],
    ingredients: ['torsk', 'rasp', 'æg', 'kartofler', 'ærter', 'citron'],
  },
  {
    id: 'fiskesuppe',
    name: 'Cremet fiskesuppe med grøntsager og dild',
    category: 'fisk',
    tags: ['suppe', 'sund'],
    dietary: ['glutenfri'],
    ingredients: ['fisk', 'gulerødder', 'løg', 'fløde', 'kartofler', 'dild'],
  },
  {
    id: 'rejer-hvidløg',
    name: 'Rejer stegt i hvidløgssmør med brød og citron',
    category: 'fisk',
    tags: ['hurtig', 'festmad'],
    dietary: [],
    ingredients: ['rejer', 'smør', 'hvidløg', 'persille', 'citron', 'brød'],
  },

  // ── PASTA ───────────────────────────────────────────────────────────────────

  {
    id: 'carbonara',
    name: 'Pasta carbonara med bacon og parmesan',
    category: 'pasta',
    tags: ['italiensk', 'hurtig'],
    dietary: [],
    ingredients: ['spaghetti', 'bacon', 'æg', 'parmesan', 'hvidløg'],
  },
  {
    id: 'pasta-pesto',
    name: 'Pasta med pesto, kylling og cherrytomater',
    category: 'pasta',
    tags: ['italiensk', 'hurtig'],
    dietary: [],
    ingredients: ['pasta', 'kylling', 'pesto', 'tomat', 'mozzarella', 'parmesan', 'hvidløg'],
  },
  {
    id: 'pasta-rejer',
    name: 'Linguine med rejer, hvidløg og persille',
    category: 'pasta',
    tags: ['italiensk', 'festmad'],
    dietary: [],
    ingredients: ['pasta', 'rejer', 'hvidløg', 'smør', 'persille', 'citron', 'tomat'],
  },
  {
    id: 'pasta-primavera',
    name: 'Pasta primavera med årstidens grøntsager og fløde',
    category: 'pasta',
    tags: ['vegetarisk', 'forår'],
    dietary: ['vegetarisk'],
    ingredients: ['pasta', 'broccoli', 'gulerødder', 'ærter', 'løg', 'hvidløg', 'fløde', 'parmesan'],
  },
  {
    id: 'pasta-kylling-bacon-karry',
    name: 'Pasta med kylling, bacon, karrydressing og spinat',
    category: 'pasta',
    tags: ['populær', 'hurtig'],
    dietary: [],
    ingredients: ['pasta', 'kylling', 'bacon', 'spinat', 'karry', 'mayonnaise', 'fløde', 'løg'],
  },

  // ── VEGETAR ─────────────────────────────────────────────────────────────────

  {
    id: 'dahl',
    name: 'Røde linser dahl med kokosmælk, basmatiris og naan',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'indisk'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['linser', 'kokosmælk', 'tomat', 'løg', 'hvidløg', 'ingefær', 'karry', 'ris'],
  },
  {
    id: 'kikærte-karry',
    name: 'Kikærtekarry med spinat, kokosmælk og basmatiris',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'indisk'],
    dietary: ['vegetarisk', 'vegansk', 'glutenfri', 'laktosefri'],
    ingredients: ['kikærter', 'spinat', 'tomat', 'løg', 'hvidløg', 'ingefær', 'kokosmælk', 'karry', 'ris'],
  },
  {
    id: 'kikærtegryde',
    name: 'Kikærtegryde med tomat, paprika og feta',
    category: 'vegetar',
    tags: ['vegetarisk', 'hurtig', 'mellemøstlig'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['kikærter', 'tomat', 'peberfrugt', 'løg', 'hvidløg', 'feta', 'spinat'],
  },
  {
    id: 'grøntsagssuppe',
    name: 'Hjemmelavet grøntsagssuppe med brød',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'sund'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['gulerødder', 'løg', 'selleri', 'kartofler', 'persille', 'brød'],
  },
  {
    id: 'tomatsuppe',
    name: 'Cremet tomatsuppe med croutoner',
    category: 'vegetar',
    tags: ['vegetarisk', 'hurtig'],
    dietary: ['vegetarisk'],
    ingredients: ['tomat', 'løg', 'hvidløg', 'fløde', 'smør', 'brød'],
  },
  {
    id: 'falafler',
    name: 'Hjemmelavede falafler med hummus og pitabrød',
    category: 'vegetar',
    tags: ['vegetarisk', 'vegansk', 'mellemøstlig'],
    dietary: ['vegetarisk', 'vegansk', 'laktosefri'],
    ingredients: ['kikærter', 'løg', 'hvidløg', 'persille', 'spidskommen', 'pitabrød', 'tomat', 'salat'],
  },
  {
    id: 'risotto',
    name: 'Champignonrisotto med parmesan og timian',
    category: 'vegetar',
    tags: ['italiensk', 'vegetarisk', 'weekend'],
    dietary: ['vegetarisk', 'glutenfri'],
    ingredients: ['risottoris', 'champignon', 'løg', 'hvidløg', 'parmesan', 'smør', 'fløde'],
  },

  // ── INTERNATIONALT ──────────────────────────────────────────────────────────

  {
    id: 'okonomiyaki',
    name: 'Okonomiyaki — japansk inspireret madpandekage',
    category: 'internationalt',
    tags: ['japansk', 'anderledes', 'hurtig'],
    dietary: [],
    ingredients: ['hvidkål', 'æg', 'mel', 'bacon', 'sojasovs', 'mayonnaise', 'purløg'],
  },
  {
    id: 'fried-rice',
    name: 'Stegt ris med æg, grøntsager og sojasovs',
    category: 'internationalt',
    tags: ['asiatisk', 'restemat', 'hurtig'],
    dietary: ['vegetarisk', 'glutenfri', 'laktosefri'],
    ingredients: ['ris', 'æg', 'sojasovs', 'løg', 'gulerødder', 'ærter', 'hvidløg'],
  },

];
